# NOTE: Before activating this workflow, it is recommended that you create a new label in your repo:
# - "auto-approve", suggested color: #8BF8BD

name: auto-approve
on:
  pull_request:
    types:
      - opened
      - labeled
      - ready_for_review
      - reopened
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout PR
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Auto-approve PRs by other users as team-tf-cdk
        if: contains(github.event.pull_request.labels.*.name, 'auto-approve') && (github.event.pull_request.user.login != 'team-tf-cdk')
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # NOTE: Replace this with the name of your token associated with the team-tf-cdk user
        run: gh pr review ${{ github.event.pull_request.number }} --approve
      - name: Auto-approve PRs by team-tf-cdk as github-actions[bot]
        if: contains(github.event.pull_request.labels.*.name, 'auto-approve') && (github.event.pull_request.user.login == 'team-tf-cdk')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token does not need to be replaced
        run: gh pr review ${{ github.event.pull_request.number }} --approve
